steps:
  # Set up cache tag based on branch/PR
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: SetupCacheVars
    entrypoint: bash
    args:
      - -c
      - |
        # Set cache tag based on branch or PR
        if [[ "$BRANCH_NAME" == "main" ]]; then
          CACHE_TAG="main-latest"
        elif [[ "$BRANCH_NAME" == "legacy" ]]; then
          CACHE_TAG="legacy-latest"
        elif [[ "$_PR_NUMBER" != "" ]]; then
          CACHE_TAG="pr-$_PR_NUMBER-latest"
        else
          # Replace slashes with hyphens for branch name
          BRANCH_SAFE=$BRANCH_NAME
          BRANCH_SAFE=$${BRANCH_SAFE//\//-}
          CACHE_TAG="$$BRANCH_SAFE-latest"
        fi
        
        # Save to a file that can be accessed by other steps
        echo "$$CACHE_TAG" > /workspace/cache_tag.txt
        echo "Using cache tag: $$CACHE_TAG"
        
        # Pull the cache image if it exists (won't fail if it doesn't)
        docker pull $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$$CACHE_TAG || true

  # Build with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: bash
    args:
      - -c
      - |
        CACHE_TAG=$$(cat /workspace/cache_tag.txt)
        docker build \
          --tag=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$COMMIT_SHA \
          --cache-from=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$$CACHE_TAG \
          --build-arg=NEXT_PUBLIC_STYTCH_PROJECT_ENV=$_NEXT_PUBLIC_STYTCH_PROJECT_ENV \
          --build-arg=NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN=$_NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN \
          --build-arg=NEXT_PUBLIC_STYTCH_APP_ID=$_NEXT_PUBLIC_STYTCH_APP_ID \
          --build-arg=NEXT_PUBLIC_LIT_RELAY_API_KEY=$_NEXT_PUBLIC_LIT_RELAY_API_KEY \
          --build-arg=NEXT_PUBLIC_LIT_CONTRACT_ADDRESS=$_NEXT_PUBLIC_LIT_CONTRACT_ADDRESS \
          --build-arg=NEXT_PUBLIC_LIT_ADDRESS=$_NEXT_PUBLIC_LIT_ADDRESS \
          .

  # Push with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$COMMIT_SHA'
      
  # Tag and push with cache tag
  - name: 'gcr.io/cloud-builders/docker'
    id: TagForCache
    entrypoint: bash
    args:
      - -c
      - |
        CACHE_TAG=$$(cat /workspace/cache_tag.txt)
        docker tag $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$COMMIT_SHA $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$$CACHE_TAG
        docker push $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$$CACHE_TAG
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        # Set tag based on branch or PR
        if [[ "$BRANCH_NAME" == "main" ]]; then
          # No tag for main branch
          TAG_OPTION=""
        elif [[ "$BRANCH_NAME" == "legacy" ]]; then
          # Tag as legacy for legacy branch
          TAG_OPTION="--tag=legacy"
        elif [[ "$_PR_NUMBER" != "" ]]; then
          # Tag with PR number for pull requests
          TAG_OPTION="--tag=pr-$_PR_NUMBER"
        else
          # Default: no tag
          TAG_OPTION=""
        fi
        
        # Execute the deploy command with dynamic tag
        # Use $$ to escape bash variables in Cloud Build YAML
        gcloud run services update $_SERVICE_NAME \
          --platform=managed \
          --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$COMMIT_SHA \
          --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID \
          --region=$_DEPLOY_REGION \
          --quiet \
          $$TAG_OPTION
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/conciliator-app/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: 9cb89cf6-252e-44ae-a6b5-4e104ca14efa
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: conciliator-456321
  _PLATFORM: managed
  _SERVICE_NAME: conciliator
  _DEPLOY_REGION: us-central1
  _NEXT_PUBLIC_STYTCH_PROJECT_ENV: test
  _NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN: public-token-test-32ccb142-bf26-4bd7-a4f6-5c3b71b94955
  _NEXT_PUBLIC_STYTCH_APP_ID: project-test-df5856de-9131-412e-bee2-f8155431b86a
  _NEXT_PUBLIC_LIT_RELAY_API_KEY: test-api-key
  _NEXT_PUBLIC_LIT_CONTRACT_ADDRESS: '0x262B5cb19B39a813C3E4366BC9d92573128139ba'
  _NEXT_PUBLIC_LIT_ADDRESS: '0xa6985f885c29cff477212ba5b2fb7679f83555b6'

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - conciliator
